# Example docker compose, update the image name and the database properties to the ones you need
version: '3'
services: 
  db:
    image: postgres
    container_name: 'postgres'
    restart: always
    environment:
      POSTGRES_PASSWORD: student
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  notebook: 
    image: 'jupyter/scipy-notebook'
    container_name: 'notebook'
    ports: 
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - .:/home/jovyan/work